name: run-code-checks

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code ğŸ§³
        uses: actions/checkout@v4

      - name: install uv ğŸŒ
        uses: astral-sh/setup-uv@v3

      - name: set up Python ğŸ
        uses: actions/setup-python@v5

      - name: install project ğŸš€
        run: uv sync --dev

      - name: lint ğŸ§¹
        run: uv run ruff check .

      - name: run tests ğŸ§ª
        run: uv run pytest

      - name: type check âŒ¨ï¸
        run: uv run mypy .

